### ISSUE TITLE
Tech debt: replace synthetic test data with empirical data for various fgbio tools

### ISSUE THREAD

**Issue by nh13** [ewels/MultiQC_TestData#145]
See comment: https://github.com/ewels/MultiQC_TestData/pull/139#issuecomment-620667475

**Comment by ewels** [comment]
And Picard 😉

**Comment by nh13** [comment]
![the deal](https://user-images.githubusercontent.com/846274/80509416-3e016080-892e-11ea-9b84-7d75b64fd8b2.gif)

**Comment by ewels** [comment]
This is a super minor nag on my part, so I'm going to close this issue and we can forget that I ever said anything 😅
