### ISSUE TITLE
example peddy 1kg data

### ISSUE THREAD

**Issue by brentp** [ewels/MultiQC_TestData#27]
1kg here is the background data for peddy. see brentp/peddy#20
[example.background_pca.json.gz](https://github.com/ewels/MultiQC_TestData/files/670808/example.background_pca.json.gz)

**Comment by ewels** [comment]
Brilliant, thanks! 👍

**Comment by ewels** [comment]
Is it usually gzipped, or is that just for this upload here?

**Comment by brentp** [comment]
just for the upload.
