### ISSUE TITLE
Can't extract Picard CollectRnaSeqMetrics information

### ISSUE THREAD

**Issue by lxhuang7** [ewels/MultiQC_TestData#30]
Hi Phil, 

As we discussed over Gitter, I have trouble to get MultiQC recognize the CollectRnaSeqMetrics results. Please find the attached an example file for you to test. Thanks!

Best regards,
Lei
[CTC-1-AA-B2.star.bam.rnaseqmetrics.txt](https://github.com/ewels/MultiQC_TestData/files/815430/CTC-1-AA-B2.star.bam.rnaseqmetrics.txt)

**Comment by ewels** [comment]
Thanks Lei! I'm moving this issue to the main MultiQC repository so that it doesn't get lost. Hope that's ok!

Phil

**Comment by lxhuang7** [comment]
Not at all. Thanks Phil!
