### ISSUE TITLE
Add testing instructions to the readme

### ISSUE THREAD

**Issue by jchorl** [ewels/MultiQC_TestData#302]
Hi!

I understand this repo contains test data for multiqc. Is there a recommended way of running these tests locally?

Where I'm at:
1. I've made some changes to multiqc
2. I want to test them

In multiqc dev docs, I see that github actions will likely run the testdata against my changes to multiqc: https://github.com/ewels/MultiQC/blob/master/.github/CONTRIBUTING.md#review-workflow

But I also want to modify testdata too. I want to add a test and run it against my branch of multiqc. Feels like adding anything in the readme could be helpful!

If I figure something out I'll PR it.

**Comment by jchorl** [comment]
I did figure this out to test https://github.com/ewels/MultiQC/pull/2170

Here's what I did:
```
docker run -it --rm \
    -v /home/j/third-party/MultiQC:/src/MultiQC \
    -v /home/j/third-party/MultiQC_TestData:/src/MultiQC_TestData \
    -w /src/MultiQC \
    python:3.12 \
    bash

pip install .
cd /src/MultiQC_TestData/data/modules/kraken
multiqc -f .
```

Not sure if this is the recommended way. If it is, I can cut a PR to document.

**Comment by ewels** [comment]
I (and I think most people) just have the two repos cloned locally with MultiQC installed locally (`pip install -e .`). Then you can do whatever you want in the test data repo and push a PR with new data if / when you want to.

This setup also makes it easy to check out different PRs on both MultiQC and the test data for development.

It's low tech, but it's served me well for 8 years now 😅  Is there something you're missing with this kind of setup?

Phil

**Comment by jchorl** [comment]
Yeah, I guess this ended up being a bit silly. It involved installing from source in one repo and running in another, which in hindsight, isn't all that bad.

Also, when you run it, do you usually `cd` into a specific testdata dir, or is there a test suite that covers all them? I noticed some `pytest` files, not sure if just blindly running `pytest` is the way to go.

Anyway, I think we can close this.

**Comment by ewels** [comment]
The `pytest` files are leftover from an aborted attempt to write unit testing for MultiQC which never went through. For now yes, I just `cd` into a specific directoriy.

There's an issue on the roadmap to set up proper unit testing, we're hoping to get to it in 2024 if all goes well: https://github.com/ewels/MultiQC/issues/2046
