### ISSUE TITLE
Help wanted: interop data

### ISSUE THREAD

**Issue by matthdsm** [ewels/MultiQC_TestData#67]
Hi Phil,

I don't know if you've had the time to take a look at the testdata I've submitted, but I'm having some issues parsing it to a suitable json structure.

Can you offer any advice about how to best structure the data dict, so we can get some nice tables?

Thanks
M

**Comment by ewels** [comment]
Hi @matthdsm,

How come you need to parse into json? I thought that they came from a standardised command? (as described in your [readme](https://github.com/ewels/MultiQC_TestData/pull/66/files#diff-a985d9c2534ff08eb003a243fca01eff)..)

If you're having to parse them yourself then they're probably not suitable for a MultiQC module, as that needs to work for whoever runs it (not tied to a specific custom script or method).

Phil

**Comment by matthdsm** [comment]
yeah, they do, I've got a csv formatted output, but I'm wondering how to best parse it in the module so the table functions can consume it.

M

**Comment by ewels** [comment]
ah wait, are you talking about the parsing code that you're adding to MultiQC in https://github.com/ewels/MultiQC/pull/589 ? (Not JSON?)

I made a start on reviewing all of the PRs yesterday but didn't make it to yours yet sorry. I'll hopefully get there soon though!

**Comment by ewels** [comment]
Gotcha, in this case it's not really tied to the test data itself as that has a static format. Let's continue the discussion on that PR instead of in the test data repo.
